[build]
  command = "bun run build"
  publish = "dist"

[[plugins]]
  package = "netlify-plugin-cache-next"

[build.environment]
  NODE_ENV = "production"
  BUN_ENV = "production"

[functions]
  node_bundler = "esbuild"
